/**
 * ts-xsd Codegen Configuration for adt-plugin-abapgit
 * 
 * Generates raw schemas with pre-generated TypeScript interfaces for abapGit object types.
 * Similar to adt-schemas, uses generated interfaces instead of runtime inference.
 * 
 * Usage:
 *   npx tsx scripts/codegen.ts
 *   npx nx run adt-plugin-abapgit:codegen
 */

// Import from built ts-xsd package
import { defineConfig, rawSchema, interfaces, indexBarrel } from '../ts-xsd/dist/generators/index.mjs';

export default defineConfig({
  // Use extensionless imports for bundler compatibility
  importExtension: '',
  sources: {
    abapgit: {
      xsdDir: 'xsd',
      outputDir: 'src/schemas/generated/schemas',
      schemas: [
        'abapgit',
        'asx',
        'clas',
        'devc',
        'doma',
        'dtel',
        'intf',
      ],
    },
  },
  generators: [
    // Generate raw schema literals with default export
    // Using resolve: true to merge imports, expand extensions and substitution groups
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: false,  // Not needed when resolve is enabled - schema is self-contained
      resolve: true,    // Merge imports, expand extensions and substitution groups
    }),
    // Generate TypeScript interfaces to ../types/ directory
    interfaces({
      filePattern: '../types/{name}.ts',
      importPattern: './{name}',  // Types are in same directory, extensionless
      generateAllTypes: true,
      addJsDoc: true,
    }),
    // Generate index.ts barrel file for schemas
    indexBarrel({
      namedExports: true,
      importExtension: '',  // Extensionless - tsx loader handles resolution
    }),
  ],

  // Generate aggregate index files after all sources are processed
  afterAll() {
    // Main index file
    const mainIndex = [
      '/**',
      ' * Auto-generated schema index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      '// Schemas',
      `export * from './schemas/index';`,
      '',
      '// Types',
      `export * from './types/index';`,
      '',
    ].join('\n');

    // Types index file - re-exports all types and defines composite types
    const typesIndex = [
      '/**',
      ' * Auto-generated types index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      `// Base types`,
      `export * from './asx';`,
      `export * from './abapgit';`,
      '',
      `// Object-specific types`,
      `export * from './clas';`,
      `export * from './devc';`,
      `export * from './doma';`,
      `export * from './dtel';`,
      `export * from './intf';`,
      '',
      `// Composite types - AbapGit wrapper + object content`,
      `import type { AbapGit } from './abapgit';`,
      `import type { VseoClassType } from './clas';`,
      `import type { DevcType } from './devc';`,
      `import type { Dd01vType } from './doma';`,
      `import type { Dd04vType } from './dtel';`,
      `import type { VseoInterfType } from './intf';`,
      '',
      `/** CLAS - Class XML structure */`,
      `export type AbapGitClas = AbapGit<VseoClassType>;`,
      '',
      `/** DEVC - Package XML structure */`,
      `export type AbapGitDevc = AbapGit<DevcType>;`,
      '',
      `/** DOMA - Domain XML structure */`,
      `export type AbapGitDoma = AbapGit<Dd01vType>;`,
      '',
      `/** DTEL - Data Element XML structure */`,
      `export type AbapGitDtel = AbapGit<Dd04vType>;`,
      '',
      `/** INTF - Interface XML structure */`,
      `export type AbapGitIntf = AbapGit<VseoInterfType>;`,
      '',
    ].join('\n');

    return [
      { path: 'src/schemas/generated/index.ts', content: mainIndex },
      { path: 'src/schemas/generated/types/index.ts', content: typesIndex },
    ];
  },
});
