/**
 * ts-xsd Codegen Configuration for adt-plugin-abapgit
 * 
 * 3-Step Pipeline:
 * 1. rawSchema() - Generate raw schema literals with `as const`
 * 2. interfaces() - Generate TypeScript interfaces from XSD
 * 3. indexBarrel() - Generate typed index exports
 * 
 * Usage:
 *   npx nx codegen adt-plugin-abapgit
 */

import { defineConfig, rawSchema, interfaces, indexBarrel } from 'ts-xsd/generators';

export default defineConfig({
  // Use extensionless imports for bundler compatibility
  importExtension: '',
  // Clean output directories before generation
  clean: true,
  sources: {
    abapgit: {
      xsdDir: 'xsd',
      outputDir: 'src/schemas/generated/schemas',
      // Only object schemas - base schemas (asx, abapgit) are included via xs:import/xs:include
      // and their types get merged into each object schema during resolution
      schemas: [
        'clas',
        'devc',
        'doma',
        'dtel',
        'intf',
      ],
    },
  },
  generators: [
    // Generate raw schema literals with default export
    // Using resolve: true to merge imports, expand extensions and substitution groups
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: false,  // Not needed when resolve is enabled - schema is self-contained
      resolve: true,    // Merge imports, expand extensions and substitution groups
    }),
    // Generate TypeScript interfaces to ../types/ directory
    interfaces({
      filePattern: '../types/{name}.ts',
      generateAllTypes: true,
      addJsDoc: true,
    }),
    // Generate index.ts barrel file for schemas
    indexBarrel({
      namedExports: true,
      importExtension: '',  // Extensionless - tsx loader handles resolution
    }),
  ],

  // Generate aggregate index files after all sources are processed
  afterAll(ctx) {
    // Get all schemas from context
    const schemas = Object.values(ctx.sources).flatMap(s => s.schemas);
    
    // Helper to capitalize first letter
    const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
    
    // Main index file
    const mainIndex = [
      '/**',
      ' * Auto-generated schema index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      '// Schemas',
      `export * from './schemas/index';`,
      '',
      '// Types',
      `export * from './types/index';`,
      '',
    ].join('\n');

    // Types index file - each schema has its own AbapGitType, export with renamed alias
    const typesIndex = [
      '/**',
      ' * Auto-generated types index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      `// Object types - AbapGitType renamed per schema to avoid conflicts`,
      ...schemas.map(s => 
        `export type { AbapGitType as ${capitalize(s)}AbapGitType } from './${s}';`
      ),
      '',
    ].join('\n');

    return [
      { path: 'src/schemas/generated/index.ts', content: mainIndex },
      { path: 'src/schemas/generated/types/index.ts', content: typesIndex },
    ];
  },
});
