/**
 * ts-xsd Codegen Configuration for adt-plugin-abapgit
 * 
 * Generates raw schemas with pre-generated TypeScript interfaces for abapGit object types.
 * Similar to adt-schemas, uses generated interfaces instead of runtime inference.
 * 
 * Usage:
 *   npx tsx scripts/codegen.ts
 *   npx nx run adt-plugin-abapgit:codegen
 */

// Import from built ts-xsd package
import { defineConfig, rawSchema, interfaces, indexBarrel } from '../ts-xsd/dist/generators/index.mjs';

export default defineConfig({
  // Use .ts extensions for Node.js native test runner compatibility
  // tsdown bundler handles stripping extensions during build
  importExtension: '.ts',
  sources: {
    abapgit: {
      xsdDir: 'xsd',
      outputDir: 'src/schemas/generated/schemas',
      schemas: [
        'abapgit',
        'asx',
        'clas',
        'devc',
        'doma',
        'dtel',
        'intf',
      ],
    },
  },
  generators: [
    // Generate raw schema literals with default export
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: true,
    }),
    // Generate TypeScript interfaces to ../types/ directory
    interfaces({
      filePattern: '../types/{name}.ts',
      importPattern: './{name}.ts',  // Types are in same directory
      generateAllTypes: true,
      addJsDoc: true,
    }),
    // Generate index.ts barrel file for schemas
    indexBarrel({
      namedExports: true,
      importExtension: '.ts',  // Use .ts for Node.js native test runner
    }),
  ],

  // Generate aggregate index files after all sources are processed
  afterAll() {
    // Main index file
    const mainIndex = [
      '/**',
      ' * Auto-generated schema index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      '// Schemas',
      `export * from './schemas/index.ts';`,
      '',
      '// Types',
      `export * from './types/index.ts';`,
      '',
    ].join('\n');

    // Types index file
    const typesIndex = [
      '/**',
      ' * Auto-generated types index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      `export * from './asx.ts';`,
      `export * from './abapgit.ts';`,
      `export * from './clas.ts';`,
      `export * from './devc.ts';`,
      `export * from './doma.ts';`,
      `export * from './dtel.ts';`,
      `export * from './intf.ts';`,
      '',
    ].join('\n');

    return [
      { path: 'src/schemas/generated/index.ts', content: mainIndex },
      { path: 'src/schemas/generated/types/index.ts', content: typesIndex },
    ];
  },
});
