import type { AdkObjectConstructor } from '../base/adk-object';
import { createAdkObjectClassWithFactory } from '../base/adk-object-factory';
import { ClassSpec } from '../namespaces/class';
import { Kind } from '../kind';

/**
 * ABAP Class object - Generated by ADK factory
 *
 * Use class.spec to access all properties directly.
 * All XML handling is delegated to ClassSpec.
 */
export const Class = createAdkObjectClassWithFactory(Kind.Class, ClassSpec);

// Export constructor type for registry
export const ClassConstructor: AdkObjectConstructor<
  InstanceType<typeof Class>
> = Class;
