import type { AdkObjectConstructor } from '../base/adk-object';
import { createAdkObjectClassWithFactory } from '../base/adk-object-factory';
import { IntfSpec } from '../namespaces/intf';
import { Kind } from '../kind';

/**
 * ABAP Interface object - Generated by ADK factory
 *
 * Use interface.spec to access all properties directly.
 * All XML handling is delegated to IntfSpec.
 */
export const Interface = createAdkObjectClassWithFactory(
  Kind.Interface,
  IntfSpec
);

// Export constructor type for registry
export const InterfaceConstructor: AdkObjectConstructor<
  InstanceType<typeof Interface>
> = Interface;
