import type { AdkObjectConstructor } from '../base/adk-object';
import { createAdkObject } from '../base/class-factory';
import { ClassAdtSchema } from '@abapify/adt-schemas';
import { Kind } from '../registry/kinds';

/**
 * ABAP Class object
 *
 * Generated by createAdkObject factory.
 * Delegates all XML I/O to ClassAdtSchema.
 */
export const Class = createAdkObject(Kind.Class, ClassAdtSchema);

// Export constructor type for registry
export const ClassConstructor: AdkObjectConstructor<InstanceType<typeof Class>> = Class;

// Export type
export type Class = InstanceType<typeof Class>;
