/**
 * Factory Generator - Wraps schemas with a factory function
 * 
 * Generates TypeScript schema files that use a factory function for wrapping.
 * This enables custom schema processing (e.g., adding parse/build methods).
 * 
 * Usage:
 *   npx ts-xsd codegen --generator=ts-xsd/generators/factory --factory=../../speci
 * 
 * Arguments:
 *   --factory  Path to factory function (relative to output dir)
 *              Default: '../schema'
 */

import type { Generator, GeneratorContext, SchemaData } from '../codegen/generator';
import { generateImports, generateSchemaLiteral } from '../codegen/generator';

/**
 * Generate header comment
 */
function generateHeader(schema: SchemaData): string {
  const lines = [
    '/**',
    ' * Auto-generated ts-xsd schema',
  ];
  
  if (schema.namespace) {
    lines.push(` * Namespace: ${schema.namespace}`);
  }
  
  if (schema.imports.length > 0) {
    lines.push(` * Imports: ${schema.imports.map(i => i.path).join(', ')}`);
  }
  
  lines.push(' * Generated by ts-xsd (factory generator)');
  lines.push(' */');
  
  return lines.join('\n');
}

const factoryGenerator: Generator = {
  generate({ schema, args }: GeneratorContext): string {
    const factoryPath = args['factory'] || '../schema';
    const lines: string[] = [];
    
    // Header comment
    lines.push(generateHeader(schema));
    lines.push('');
    
    // Import factory function
    lines.push(`import schema from '${factoryPath}';`);
    
    // Import dependencies
    if (schema.imports.length > 0) {
      lines.push(generateImports(schema.imports));
    }
    lines.push('');
    
    // Export wrapped schema (use 'as const' to preserve literal types for InferXsd)
    lines.push(`export default schema(${generateSchemaLiteral(schema)} as const);`);
    lines.push('');
    
    return lines.join('\n');
  },
  
  generateIndex(schemas: string[]): string {
    const lines = [
      '/**',
      ' * Auto-generated index file',
      ' * Generated by ts-xsd',
      ' */',
      '',
      ...schemas.map(name => `export { default as ${name} } from './${name}';`),
      '',
    ];
    
    return lines.join('\n');
  },
};

export default factoryGenerator;
