/**
 * Factory Generator - Wraps schemas with a factory function
 * 
 * Generates TypeScript schema files that use a factory function for wrapping.
 * This enables custom schema processing (e.g., adding parse/build methods).
 * 
 * @example
 * ```typescript
 * import { defineConfig, factory } from 'ts-xsd';
 * 
 * export default defineConfig({
 *   generator: factory({ path: '../../speci' }),
 * });
 * ```
 */

import type { Generator, GeneratorContext, SchemaData } from '../codegen/generator';
import { generateImports, generateSchemaLiteral } from '../codegen/generator';

/**
 * Factory generator options
 */
export interface FactoryOptions {
  /** 
   * Path to factory function (relative to output directory)
   * @default '../schema'
   */
  path?: string;
}

/**
 * Generate header comment
 */
function generateHeader(schema: SchemaData): string {
  const lines = [
    '/**',
    ' * Auto-generated ts-xsd schema',
  ];
  
  if (schema.namespace) {
    lines.push(` * Namespace: ${schema.namespace}`);
  }
  
  if (schema.imports.length > 0) {
    lines.push(` * Imports: ${schema.imports.map(i => i.path).join(', ')}`);
  }
  
  lines.push(' * Generated by ts-xsd (factory generator)');
  lines.push(' */');
  
  return lines.join('\n');
}

/**
 * Create a factory generator with custom options
 * 
 * @example
 * ```typescript
 * // Default factory path
 * const gen = factory();
 * 
 * // Custom factory path
 * const gen = factory({ path: '../../speci' });
 * ```
 */
export function factory(options: FactoryOptions = {}): Generator {
  const factoryPath = options.path || '../schema';
  
  return {
    generate({ schema }: GeneratorContext): string {
      const lines: string[] = [];
      
      // Header comment
      lines.push(generateHeader(schema));
      lines.push('');
      
      // Import factory function
      lines.push(`import schema from '${factoryPath}';`);
      
      // Import dependencies
      if (schema.imports.length > 0) {
        lines.push(generateImports(schema.imports));
      }
      lines.push('');
      
      // Export wrapped schema (use 'as const' to preserve literal types for InferXsd)
      lines.push(`export default schema(${generateSchemaLiteral(schema)} as const);`);
      lines.push('');
      
      return lines.join('\n');
    },
    
    generateIndex(schemas: string[]): string {
      const lines = [
        '/**',
        ' * Auto-generated index file',
        ' * Generated by ts-xsd',
        ' */',
        '',
        ...schemas.map(name => `export { default as ${name} } from './${name}';`),
        '',
      ];
      
      return lines.join('\n');
    },
    
    generateStub(schemaName: string): string {
      return `/**
 * Stub schema for ${schemaName}
 * This schema is referenced but not available.
 */
import schema from '${factoryPath}';

export default schema({
  elements: {},
});
`;
    },
  };
}

// Default export for backward compatibility
export default factory();
