/**
 * Interfaces Generator
 * 
 * Generates TypeScript interfaces from XSD schemas using ts-morph.
 * This wraps the existing interface-generator.ts implementation.
 * 
 * Output: `export interface TypeName { ... }`
 */

import type { GeneratorPlugin, TransformContext, GeneratedFile, SchemaInfo } from '../codegen/types';
import { generateInterfacesWithDeps } from '../codegen/interface-generator';
import type { GeneratorOptions } from '../codegen/interface-generator';
import type { Schema } from '../xsd/types';

// ============================================================================
// Options
// ============================================================================

export interface InterfacesOptions extends GeneratorOptions {
  /** Output file name pattern. Use {name} for schema name (default: '{name}.types.ts') */
  filePattern?: string;
  /** Import path pattern for cross-schema type imports. Use {name} for schema name (default: './{name}.types') */
  importPattern?: string;
  /** Add file header comment */
  header?: boolean;
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Create an interfaces generator plugin
 * 
 * Generates TypeScript interfaces from XSD complex types.
 * This solves the TS2589 "Type instantiation is excessively deep" problem
 * by generating interfaces at build time instead of relying on compile-time inference.
 * 
 * @example
 * ```ts
 * import { rawSchema, interfaces, indexBarrel } from 'ts-xsd/generators';
 * 
 * export default defineConfig({
 *   generators: [
 *     rawSchema(),
 *     interfaces({ generateAllTypes: true }),  // Generate all complex types
 *     indexBarrel(),
 *   ],
 * });
 * ```
 */
export function interfaces(options: InterfacesOptions = {}): GeneratorPlugin {
  const {
    filePattern = '{name}.types.ts',
    importPattern = './{name}.types',
    header = true,
    ...generatorOptions
  } = options;

  return {
    name: 'interfaces',

    transform(ctx: TransformContext): GeneratedFile[] {
      const { schema, source, allSchemas } = ctx;
      
      // Link schemas: resolve $imports from allSchemas
      const linkedSchema = linkSchemaImports(schema.schema, allSchemas, schema.name);
      
      // Use the core generator with dependency tracking
      const result = generateInterfacesWithDeps(linkedSchema, {
        generateAllTypes: true,  // Default to generating all types
        addJsDoc: true,
        ...generatorOptions,
      });

      // Build output
      const lines: string[] = [];

      // Header
      if (header) {
        lines.push(
          '/**',
          ' * Auto-generated TypeScript interfaces from XSD',
          ' * ',
          ' * DO NOT EDIT - Generated by ts-xsd codegen',
          ` * Source: ${source.name}/${schema.name}.xsd`,
          ' */',
          '',
        );
      }

      // Add imports for external types
      // Map namespace URIs to schema names using import declarations
      const imports = schema.schema.import;
      
      if (result.externalTypes.size > 0) {
        // Build a map from namespace URI to schema filename
        const nsToSchemaFile = new Map<string, string>();
        
        if (imports && Array.isArray(imports)) {
          for (const imp of imports) {
            if (imp.namespace && imp.schemaLocation) {
              // Extract filename without extension from schemaLocation
              const schemaFile = imp.schemaLocation.replace(/\.xsd$/, '');
              nsToSchemaFile.set(imp.namespace, schemaFile);
            }
          }
        }
        
        // Group external types by their source schema file
        const typesByFile = new Map<string, string[]>();
        
        for (const [namespace, types] of result.externalTypes) {
          // Find the schema file for this namespace
          const schemaFile = nsToSchemaFile.get(namespace);
          if (schemaFile && types.length > 0) {
            const existing = typesByFile.get(schemaFile) || [];
            typesByFile.set(schemaFile, [...existing, ...types]);
          }
        }
        
        // Generate import statements
        for (const [schemaFile, types] of typesByFile) {
          const uniqueTypes = [...new Set(types)].sort();
          const importPath = importPattern.replace('{name}', schemaFile);
          lines.push(`import type { ${uniqueTypes.join(', ')} } from '${importPath}';`);
        }
        
        if (typesByFile.size > 0) {
          lines.push('');
        }
      }

      lines.push(result.code);

      // Add substitution values interfaces and specialized interfaces
      // e.g., interface DomaValuesType { DD01V: Dd01vType; DD07V_TAB?: Dd07vTabType; }
      //       interface AbapGitDoma { abap: { values: DomaValuesType; version?: string; }; ... }
      if (result.substitutionAliases.length > 0) {
        lines.push('');
        lines.push('// Substitution values types and specialized interfaces');
        
        for (const alias of result.substitutionAliases) {
          // Generate the values interface with element names as properties
          lines.push(`/** Values type for ${alias.aliasName} with element names as properties */`);
          lines.push(`export interface ${alias.valuesTypeName} {`);
          for (const el of alias.elements) {
            const optional = el.required ? '' : '?';
            lines.push(`    ${el.elementName}${optional}: ${el.typeName};`);
          }
          lines.push('}');
          lines.push('');
          
          // Generate a full interface instead of type alias to get proper element access
          // This replaces AbapValuesType<T> with the concrete values type
          lines.push(`/** ${alias.genericType} specialized for ${schema.name} object type */`);
          lines.push(`export interface ${alias.aliasName} {`);
          lines.push(`    abap: {`);
          lines.push(`        values: ${alias.valuesTypeName};`);
          lines.push(`        version?: string;`);
          lines.push(`    };`);
          lines.push(`    version: string;`);
          lines.push(`    serializer: string;`);
          lines.push(`    serializer_version: string;`);
          lines.push(`}`);
        }
      }

      const fileName = filePattern.replace('{name}', schema.name);

      return [{
        path: fileName,
        content: lines.join('\n'),
      }];
    },
  };
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Link schema imports by resolving schemaLocation references to actual schema objects.
 * Also includes ALL schemas as $imports so substitution groups can be resolved
 * across the entire schema set (not just direct imports).
 * 
 * This is necessary because substitution groups work in reverse:
 * - asx.xsd defines abstract element Schema
 * - doma.xsd imports asx.xsd and defines DD01V substituting for Schema
 * - When generating asx.types.ts, we need to know about DD01V from doma.xsd
 */
function linkSchemaImports(
  schema: Schema,
  allSchemas: Map<string, SchemaInfo>,
  schemaName: string
): Schema {
  // Include ALL schemas as $imports so substitution groups can be resolved
  // This allows finding substitutes defined in any schema, not just direct imports
  const $imports: Schema[] = [];
  
  for (const [_name, schemaInfo] of allSchemas) {
    // Skip self-reference
    if (schemaInfo.schema === schema) continue;
    $imports.push(schemaInfo.schema);
  }

  // Return schema with $imports populated and $filename set
  return {
    ...schema,
    $imports,
    $filename: schema.$filename ?? `${schemaName}.xsd`,
  };
}
