/**
 * Interfaces Generator
 * 
 * Generates TypeScript interfaces from XSD schemas using ts-morph.
 * 
 * Two modes:
 * 1. Without importPattern: Uses resolveSchema to flatten all types (no imports/extends)
 * 2. With importPattern: Preserves inheritance with proper imports and extends clauses
 * 
 * Output: `export interface TypeName { ... }`
 */

import type { GeneratorPlugin, TransformContext, GeneratedFile } from '../codegen/types';
import { generateSimpleInterfaces } from '../codegen/interface-generator';
import type { GeneratorOptions } from '../codegen/interface-generator';
import { resolveSchema } from '../xsd/resolve';

// ============================================================================
// Options
// ============================================================================

export interface InterfacesOptions extends GeneratorOptions {
  /** Output file name pattern. Use {name} for schema name, {source} for source name (default: '{name}.types.ts') */
  filePattern?: string;
  /** Add file header comment */
  header?: boolean;
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Create an interfaces generator plugin
 * 
 * Generates TypeScript interfaces from XSD complex types.
 * This solves the TS2589 "Type instantiation is excessively deep" problem
 * by generating interfaces at build time instead of relying on compile-time inference.
 * 
 * @example
 * ```ts
 * import { rawSchema, interfaces, indexBarrel } from 'ts-xsd/generators';
 * 
 * export default defineConfig({
 *   generators: [
 *     rawSchema(),
 *     interfaces({ generateAllTypes: true }),  // Flattened (no imports)
 *     indexBarrel(),
 *   ],
 * });
 * ```
 * 
 * @example With imports and extends
 * ```ts
 * export default defineConfig({
 *   generators: [
 *     rawSchema(),
 *     interfaces({ 
 *       generateAllTypes: true,
 *       importPattern: './{name}.types',  // Enables imports + extends
 *     }),
 *   ],
 * });
 * ```
 */
export function interfaces(options: InterfacesOptions = {}): GeneratorPlugin {
  const {
    filePattern = '{name}.types.ts',
    header = true,
    ...generatorOptions
  } = options;

  return {
    name: 'interfaces',

    transform(ctx: TransformContext): GeneratedFile[] {
      const { schema, source } = ctx;
      
      // When importPattern is set, use the original unresolved schema
      // This preserves the distinction between local and imported types
      // The generator will use $imports to look up types from other schemas
      //
      // When importPattern is NOT set, resolve the schema to flatten all types
      // This generates all types inline without imports/extends
      const targetSchema = generatorOptions.importPattern
        ? schema.schema  // Original schema with $imports for extends/import generation
        : resolveSchema(schema.schema);  // Flattened schema for inline generation

      // Generate interfaces using the simplified generator
      const code = generateSimpleInterfaces(targetSchema, {
        generateAllTypes: true,
        addJsDoc: true,
        ...generatorOptions,
      });

      // Build output
      const lines: string[] = [];

      // Header
      if (header) {
        lines.push(
          '/**',
          ' * Auto-generated TypeScript interfaces from XSD',
          ' * ',
          ' * DO NOT EDIT - Generated by ts-xsd codegen',
          ` * Source: ${source.name}/${schema.name}.xsd`,
          ' */',
          '',
        );
      }

      lines.push(code);

      const fileName = filePattern
        .replace('{name}', schema.name)
        .replace('{source}', source.name);

      return [{
        path: fileName,
        content: lines.join('\n'),
      }];
    },
  };
}
