/**
 * Raw Generator - Default generator for ts-xsd
 * 
 * Generates plain TypeScript schema files with XsdSchema type.
 * 
 * @example
 * ```typescript
 * import { defineConfig, raw } from 'ts-xsd';
 * 
 * export default defineConfig({
 *   generator: raw(),
 * });
 * ```
 */

import type { Generator, GeneratorContext, SchemaData } from '../codegen/generator';
import { generateImports, generateSchemaLiteral } from '../codegen/generator';

/**
 * Raw generator options
 */
export interface RawOptions {
  /** 
   * Import path for XsdSchema type
   * @default 'ts-xsd'
   */
  typesFrom?: string;
}

/**
 * Generate header comment
 */
function generateHeader(schema: SchemaData): string {
  const lines = [
    '/**',
    ' * Auto-generated ts-xsd schema',
  ];
  
  if (schema.namespace) {
    lines.push(` * Namespace: ${schema.namespace}`);
  }
  
  if (schema.imports.length > 0) {
    lines.push(` * Imports: ${schema.imports.map(i => i.path).join(', ')}`);
  }
  
  lines.push(' * Generated by ts-xsd');
  lines.push(' */');
  
  return lines.join('\n');
}

/**
 * Create a raw generator with custom options
 * 
 * @example
 * ```typescript
 * // Default
 * const gen = raw();
 * 
 * // Custom types import
 * const gen = raw({ typesFrom: '../types' });
 * ```
 */
export function raw(options: RawOptions = {}): Generator {
  const typesFrom = options.typesFrom || 'ts-xsd';
  
  return {
    generate({ schema }: GeneratorContext): string {
      const lines: string[] = [];
      
      // Header comment
      lines.push(generateHeader(schema));
      lines.push('');
      
      // Import XsdSchema type
      lines.push(`import type { XsdSchema } from '${typesFrom}';`);
      
      // Import dependencies
      if (schema.imports.length > 0) {
        lines.push(generateImports(schema.imports));
      }
      lines.push('');
      
      // Export schema
      lines.push(`export default ${generateSchemaLiteral(schema)} as const satisfies XsdSchema;`);
      lines.push('');
      
      return lines.join('\n');
    },
    
    generateIndex(schemas: string[]): string {
      // Convert hyphenated names to camelCase for valid JS identifiers
      const toExportName = (name: string) => 
        name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      
      const lines = [
        '/**',
        ' * Auto-generated index file',
        ' * Generated by ts-xsd',
        ' */',
        '',
        ...schemas.map(name => `export { default as ${toExportName(name)} } from './${name}';`),
        '',
      ];
      
      return lines.join('\n');
    },
    
    generateStub(schemaName: string): string {
      return `/**
 * Stub schema for ${schemaName}
 * This schema is referenced but not available.
 */
import type { XsdSchema } from '${typesFrom}';

export default {
  elements: {},
} as const satisfies XsdSchema;
`;
    },
  };
}

// Default export for backward compatibility
export default raw();
