/**
 * Raw Generator - Default generator for ts-xsd
 * 
 * Generates plain TypeScript schema files with XsdSchema type.
 * 
 * Usage:
 *   npx ts-xsd codegen --generator=ts-xsd/generators/raw
 *   (or omit --generator, this is the default)
 */

import type { Generator, GeneratorContext, SchemaData } from '../codegen/generator';
import { generateImports, generateSchemaLiteral } from '../codegen/generator';

/**
 * Generate header comment
 */
function generateHeader(schema: SchemaData): string {
  const lines = [
    '/**',
    ' * Auto-generated ts-xsd schema',
  ];
  
  if (schema.namespace) {
    lines.push(` * Namespace: ${schema.namespace}`);
  }
  
  if (schema.imports.length > 0) {
    lines.push(` * Imports: ${schema.imports.map(i => i.path).join(', ')}`);
  }
  
  lines.push(' * Generated by ts-xsd');
  lines.push(' */');
  
  return lines.join('\n');
}

const rawGenerator: Generator = {
  generate({ schema }: GeneratorContext): string {
    const lines: string[] = [];
    
    // Header comment
    lines.push(generateHeader(schema));
    lines.push('');
    
    // Import XsdSchema type
    lines.push("import type { XsdSchema } from 'ts-xsd';");
    
    // Import dependencies
    if (schema.imports.length > 0) {
      lines.push(generateImports(schema.imports));
    }
    lines.push('');
    
    // Export schema
    lines.push(`export default ${generateSchemaLiteral(schema)} as const satisfies XsdSchema;`);
    lines.push('');
    
    return lines.join('\n');
  },
  
  generateIndex(schemas: string[]): string {
    const lines = [
      '/**',
      ' * Auto-generated index file',
      ' * Generated by ts-xsd',
      ' */',
      '',
      ...schemas.map(name => `export { default as ${name} } from './${name}';`),
      '',
    ];
    
    return lines.join('\n');
  },
};

export default rawGenerator;
