/**
 * Simple Interfaces Generator
 * 
 * Generates TypeScript interfaces from XSD schemas using a simplified approach.
 * This generator uses mergeAll to flatten all types into a single schema first,
 * then generates interfaces without needing to traverse $imports.
 * 
 * Key benefits over the standard `interfaces` generator:
 * - Simpler implementation (~650 lines vs ~2500 lines)
 * - No cross-schema type resolution needed
 * - All types are local to the merged schema
 * - Better for schemas with complex include/import chains
 * 
 * Output: `export interface TypeName { ... }`
 */

import type { GeneratorPlugin, TransformContext, GeneratedFile } from '../codegen/types';
import { generateSimpleInterfaces, type SimpleGeneratorOptions } from '../codegen/interface-generator';
import { resolveSchema } from '../xsd/resolve';

// ============================================================================
// Options
// ============================================================================

export interface SimpleInterfacesOptions extends SimpleGeneratorOptions {
  /** Output file name pattern. Use {name} for schema name, {source} for source name (default: '{name}.types.ts') */
  filePattern?: string;
  /** Add file header comment */
  header?: boolean;
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Create a simple interfaces generator plugin
 * 
 * Generates TypeScript interfaces from XSD complex types using a simplified approach.
 * The schema is first merged (all includes/imports flattened) before generating interfaces.
 * 
 * @example
 * ```ts
 * import { rawSchema, simpleInterfaces, indexBarrel } from 'ts-xsd/generators';
 * 
 * export default defineConfig({
 *   generators: [
 *     rawSchema(),
 *     simpleInterfaces({ generateAllTypes: true }),  // Generate all complex types
 *     indexBarrel(),
 *   ],
 * });
 * ```
 */
export function simpleInterfaces(options: SimpleInterfacesOptions = {}): GeneratorPlugin {
  const {
    filePattern = '{name}.types.ts',
    header = true,
    ...generatorOptions
  } = options;

  return {
    name: 'simple-interfaces',

    transform(ctx: TransformContext): GeneratedFile[] {
      const { schema, source } = ctx;
      
      // Merge all includes/imports into a single flat schema with ALL elements
      // This includes referenced elements needed for resolving element refs
      const mergedSchema = resolveSchema(schema.schema);
      
      // Generate interfaces using the simplified generator
      const code = generateSimpleInterfaces(mergedSchema, {
        generateAllTypes: true,  // Default to generating all types
        addJsDoc: true,
        ...generatorOptions,
      });

      // Build output
      const lines: string[] = [];

      // Header
      if (header) {
        lines.push(
          '/**',
          ' * Auto-generated TypeScript interfaces from XSD',
          ' * ',
          ' * DO NOT EDIT - Generated by ts-xsd codegen (simple-interfaces)',
          ` * Source: ${source.name}/${schema.name}.xsd`,
          ' */',
          '',
        );
      }

      lines.push(code);

      const fileName = filePattern
        .replace('{name}', schema.name)
        .replace('{source}', source.name);

      return [{
        path: fileName,
        content: lines.join('\n'),
      }];
    },
  };
}
