import type { AdkObjectConstructor } from '../base/adk-object';
import { createAdkObject } from '../base/class-factory';
import { DdicDomainAdtSchema } from '@abapify/adt-schemas';
import { Kind } from '../registry/kinds';

/**
 * ABAP Domain object
 *
 * Generated by createAdkObject factory.
 * Delegates all XML I/O to DdicDomainAdtSchema.
 */
export const Domain = createAdkObject(Kind.Domain, DdicDomainAdtSchema);

// Export constructor type for registry
export const DomainConstructor: AdkObjectConstructor<InstanceType<typeof Domain>> = Domain;

// Export type
export type Domain = InstanceType<typeof Domain>;
