/**
 * ts-xsd Codegen Configuration for adt-schemas
 * 
 * Generates raw schema literals and TypeScript interfaces from SAP ADT XSD files.
 * Following the same pattern as adt-plugin-abapgit.
 * 
 * Output structure:
 *   src/schemas/generated/
 *   ├── schemas/
 *   │   ├── sap/
 *   │   ├── custom/
 *   │   └── index.ts
 *   ├── types/
 *   │   ├── sap/
 *   │   ├── custom/
 *   │   └── index.ts
 *   └── index.ts
 * 
 * Usage:
 *   npx nx run adt-schemas:codegen
 */

import { defineConfig, rawSchema, interfaces } from 'ts-xsd/generators';

// SAP schemas list
const sapSchemas = [
  'atom',
  'adtcore',
  'abapsource',
  'abapoo',
  'classes',
  'interfaces',
  'packagesV1',
  'atc',
  'atcexemption',
  'atcfinding',
  'atcinfo',
  'atcobject',
  'atcresult',
  'atcresultquery',
  'atctagdescription',
  'atcworklist',
  'transportmanagment',
  'transportsearch',
  'configuration',
  'configurations',
  'checkrun',
  'checklist',
  'debugger',
  'logpoint',
  'traces',
  'quickfixes',
  'log',
  'templatelink',
];

// Custom schemas list
const customSchemas = [
  'atomExtended',
  'discovery',
  'Ecore',
  'http',
  'templatelinkExtended',
  'transportfind',
  'transportmanagmentCreate',
  'transportmanagmentSingle',
];

export default defineConfig({
  // Use extensionless imports for bundler compatibility
  importExtension: '',
  sources: {
    sap: {
      xsdDir: '.xsd/sap',
      outputDir: 'src/schemas/generated/schemas/sap',
      schemas: sapSchemas,
    },
    custom: {
      xsdDir: '.xsd/custom',
      outputDir: 'src/schemas/generated/schemas/custom',
      schemas: customSchemas,
    },
  },
  generators: [
    // Generate raw schema literals with default export
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: true,
    }),
    // Generate TypeScript interfaces to types/{source}/ directory
    interfaces({
      filePattern: '../../types/{source}/{name}.types.ts',
      importPattern: './{name}.types',
      generateAllTypes: true,
      addJsDoc: true,
    }),
  ],

  // Generate schema and type index files (main index is generated by typedSchemas)
  afterAll() {
    // SAP schemas index
    const sapSchemasIndex = [
      '/**',
      ' * Auto-generated SAP schemas index',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      ...sapSchemas.map(s => `export { default as ${s.replace(/-/g, '')} } from './${s}';`),
      '',
    ].join('\n');

    // Custom schemas index
    const customSchemasIndex = [
      '/**',
      ' * Auto-generated custom schemas index',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      ...customSchemas.map(s => `export { default as ${s.replace(/-/g, '')} } from './${s}';`),
      '',
    ].join('\n');

    // Schemas aggregate index
    const schemasIndex = [
      '/**',
      ' * Auto-generated schema index',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      `export * from './sap';`,
      `export * from './custom';`,
      '',
    ].join('\n');

    // NOTE: Types are NOT re-exported via barrel files to avoid duplicate export conflicts.
    // Types are internal to each schema and used for typed wrappers.
    // Import types directly from: ./types/{source}/{schema}.types
    // e.g., import type { AbapClass } from './types/sap/classes.types';

    // Generate typed.ts - re-export raw schemas wrapped with typed()
    // Each schema exports its default as a typed schema using InferSchema
    const typedLines: string[] = [
      '/**',
      ' * Auto-generated typed schema exports',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' * ',
      ' * All schemas wrapped with typed() for parse/build methods.',
      ' * Type inference uses InferSchema from ts-xsd.',
      ' * ',
      ' * @example',
      ' * import { classes } from \'adt-schemas\';',
      ' * const data = classes.parse(xml);  // data is fully typed!',
      ' */',
      '',
      `import { typed } from '../../speci';`,
      `import type { InferSchema, SchemaLike } from 'ts-xsd';`,
      '',
      '// SAP schemas',
    ];

    // Reserved words that can't be used as variable names
    const reservedWords = new Set([
      'break', 'case', 'catch', 'continue', 'debugger', 'default', 'delete',
      'do', 'else', 'finally', 'for', 'function', 'if', 'in', 'instanceof',
      'new', 'return', 'switch', 'this', 'throw', 'try', 'typeof', 'var',
      'void', 'while', 'with', 'class', 'const', 'enum', 'export', 'extends',
      'import', 'super', 'implements', 'interface', 'let', 'package', 'private',
      'protected', 'public', 'static', 'yield',
    ]);

    const toExportName = (name: string) => {
      const cleaned = name.replace(/-/g, '');
      return reservedWords.has(cleaned) ? `${cleaned}Schema` : cleaned;
    };

    // Generate typed exports for SAP schemas
    for (const schemaName of sapSchemas) {
      const exportName = toExportName(schemaName);
      const importName = `_${schemaName.replace(/-/g, '')}`;
      typedLines.push(`import ${importName} from './schemas/sap/${schemaName}';`);
      typedLines.push(`export const ${exportName} = typed<InferSchema<typeof ${importName}>>(${importName} as SchemaLike);`);
    }

    typedLines.push('');
    typedLines.push('// Custom schemas');

    // Generate typed exports for custom schemas
    for (const schemaName of customSchemas) {
      const exportName = toExportName(schemaName);
      const importName = `_${schemaName.replace(/-/g, '')}`;
      typedLines.push(`import ${importName} from './schemas/custom/${schemaName}';`);
      typedLines.push(`export const ${exportName} = typed<InferSchema<typeof ${importName}>>(${importName} as SchemaLike);`);
    }

    typedLines.push('');
    const typedIndex = typedLines.join('\n');

    // Main index - exports typed schemas only (raw schemas available via ./schemas)
    // NOTE: We don't re-export raw schemas here to avoid duplicate export conflicts
    // with typed schemas that have the same name (e.g., classes, interfaces)
    const mainIndex = [
      '/**',
      ' * Auto-generated schema index',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' * ',
      ' * Typed schemas with parse/build methods.',
      ' * For raw schemas, import from \'adt-schemas/schemas\'',
      ' * ',
      ' * @example',
      ' * import { classes } from \'adt-schemas\';',
      ' * const data = classes.parse(xml);  // data is fully typed!',
      ' */',
      '',
      `// Typed schemas with parse/build methods`,
      `export * from './typed';`,
      '',
    ].join('\n');

    return [
      { path: 'src/schemas/generated/schemas/sap/index.ts', content: sapSchemasIndex },
      { path: 'src/schemas/generated/schemas/custom/index.ts', content: customSchemasIndex },
      { path: 'src/schemas/generated/schemas/index.ts', content: schemasIndex },
      { path: 'src/schemas/generated/typed.ts', content: typedIndex },
      { path: 'src/schemas/generated/index.ts', content: mainIndex },
    ];
  },
});
