/**
 * ts-xsd Codegen Configuration for adt-schemas
 * 
 * Generates raw schema literals from SAP ADT XSD files.
 * 
 * Usage:
 *   npx tsx scripts/codegen.ts
 *   npx nx run adt-schemas:codegen
 */

// Import from built ts-xsd package
import { defineConfig, rawSchema, indexBarrel } from '../ts-xsd/dist/generators/index.mjs';

export default defineConfig({
  sources: {
    sap: {
      xsdDir: '.xsd/sap',
      outputDir: 'src/schemas/generated/schemas/sap',
      schemas: [
        // Base schemas
        'atom',
        'adtcore',
        'abapsource',
        
        // OO types
        'abapoo',
        'classes',
        'interfaces',
        
        // Packages
        'packagesV1',
        
        // ATC (ABAP Test Cockpit)
        'atc',
        'atcresult',
        'atcworklist',
        
        // Transport
        'transportmanagment',
        'transportsearch',
        
        // Configuration
        'configuration',
        'configurations',
        
        // Checks & Activation
        'checkrun',
        'checklist',
        
        // Debugging
        'debugger',
        'logpoint',
        'traces',
        
        // Refactoring
        'quickfixes',
        
        // Other
        'log',
        'templatelink',
      ],
    },
    custom: {
      xsdDir: '.xsd/custom',
      outputDir: 'src/schemas/generated/schemas/custom',
      schemas: [
        'atomExtended',
        'discovery',
        'Ecore',
        'http',
        'templatelinkExtended',
        'transportfind',
        'transportmanagment-create',
        'transportmanagment-single',
      ],
    },
  },
  generators: [
    // Generate raw schema literals with default export
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: true,
    }),
    // Generate index.ts barrel file for each source
    indexBarrel(),
  ],

  // Generate aggregate schemas/index.ts after all sources are processed
  afterAll() {
    const content = [
      '/**',
      ' * Auto-generated schema index',
      ' * ',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      '// SAP schemas',
      `export * from './sap';`,
      '',
      '// Custom schemas',
      `export * from './custom';`,
      '',
    ].join('\n');

    return [{ path: 'src/schemas/generated/schemas/index.ts', content }];
  },
});
