/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/oo
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, platform:/plugin/com.sap.adt.tools.abapsource/model/abapsource.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Abapsource from './abapsource';

export default {
  ns: 'http://www.sap.com/adt/oo',
  prefix: 'oo',
  include: [Adtcore, Abapsource],
  elements: {
    AbapOoObject: {
    },
  },
} as const satisfies XsdSchema;
