/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/abapsource
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/adt/abapsource',
  prefix: 'abapsource',
  root: 'syntaxConfiguration',
  include: [Adtcore, Atom],
  elements: {
    AbapSourceMainObject: {
    },
    AbapSourceTemplate: {
      sequence: [
        { name: 'property', type: 'AbapSourceTemplateProperty', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AbapSourceTemplateProperty: {
    },
    AbapSourceObject: {
    },
    AbapSyntaxConfiguration: {
      sequence: [
        { name: 'language', type: 'AbapLanguage', minOccurs: 0 },
        { name: 'objectUsage', type: 'AbapObjectUsage', minOccurs: 0 },
      ],
    },
    AbapSyntaxConfigurations: {
    },
    AbapLanguage: {
      sequence: [
        { name: 'version', type: 'string', minOccurs: 0 },
        { name: 'description', type: 'string', minOccurs: 0 },
      ],
    },
    AbapObjectUsage: {
      attributes: [
        { name: 'restricted', type: 'boolean' },
      ],
    },
  },
} as const satisfies XsdSchema;
