/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/core
 * Imports: atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/adt/core',
  prefix: 'core',
  root: 'content',
  include: [Atom],
  elements: {
    AdtObject: {
      sequence: [
        { name: 'containerRef', type: 'AdtObjectReference', minOccurs: 0 },
        { name: 'adtTemplate', type: 'AdtTemplate', minOccurs: 0 },
      ],
      attributes: [
        { name: 'name', type: 'string', required: true },
        { name: 'type', type: 'string', required: true },
        { name: 'changedBy', type: 'string' },
        { name: 'changedAt', type: 'date' },
        { name: 'createdAt', type: 'date' },
        { name: 'createdBy', type: 'string' },
        { name: 'version', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'descriptionTextLimit', type: 'number' },
        { name: 'language', type: 'string' },
      ],
    },
    AdtMainObject: {
    },
    AdtObjectReferenceList: {
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtObjectReference: {
      sequence: [
        { name: 'extension', type: 'AdtExtension', minOccurs: 0 },
      ],
      attributes: [
        { name: 'uri', type: 'string' },
        { name: 'parentUri', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'packageName', type: 'string' },
        { name: 'description', type: 'string' },
      ],
    },
    AdtExtension: {
    },
    AdtTemplate: {
      sequence: [
        { name: 'adtProperty', type: 'AdtTemplateProperty', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtTemplateProperty: {
    },
    AdtPackageReference: {
    },
    AdtSwitchReference: {
    },
    AdtContent: {
    },
  },
} as const satisfies XsdSchema;
