/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.sap.com/adt/atc',
  prefix: 'atc',
  root: 'customizing',
  elements: {
    AtcCustomizing: {
      sequence: [
        { name: 'properties', type: 'AtcProperties' },
        { name: 'exemption', type: 'AtcExemption' },
        { name: 'scaAttributes', type: 'ScaAttributes', minOccurs: 0 },
      ],
    },
    AtcProperties: {
      sequence: [
        { name: 'property', type: 'AtcProperty', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcProperty: {
      attributes: [
        { name: 'name', type: 'string' },
        { name: 'value', type: 'string' },
      ],
    },
    AtcExemption: {
      sequence: [
        { name: 'reasons', type: 'AtcReasons' },
        { name: 'validities', type: 'AtcValidities' },
      ],
    },
    AtcReasons: {
      sequence: [
        { name: 'reason', type: 'AtcReason', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcReason: {
      attributes: [
        { name: 'id', type: 'string' },
        { name: 'justificationMandatory', type: 'boolean' },
        { name: 'title', type: 'string' },
      ],
    },
    AtcValidities: {
      sequence: [
        { name: 'validity', type: 'AtcValidity', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcValidity: {
      attributes: [
        { name: 'id', type: 'string' },
        { name: 'value', type: 'string' },
      ],
    },
    ScaAttributes: {
      sequence: [
        { name: 'scaAttribute', type: 'ScaAttribute', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    ScaAttribute: {
      attributes: [
        { name: 'attributeName', type: 'string' },
        { name: 'refAttributeName', type: 'string' },
        { name: 'label', type: 'boolean' },
        { name: 'labelS', type: 'string' },
        { name: 'labelM', type: 'string' },
        { name: 'labelL', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
