/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/finding
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/adt/atc/finding',
  prefix: 'finding',
  root: 'remarks',
  include: [Adtcore, Atom],
  elements: {
    AtcQuickfixes: {
      attributes: [
        { name: 'manual', type: 'boolean' },
        { name: 'automatic', type: 'boolean' },
        { name: 'pseudo', type: 'boolean' },
        { name: 'ai_enabled', type: 'boolean' },
        { name: 'aiBasedQF', type: 'boolean' },
      ],
    },
    AtcTag: {
      attributes: [
        { name: 'name', type: 'string' },
        { name: 'value', type: 'string' },
      ],
    },
    AtcTags: {
      sequence: [
        { name: 'tag', type: 'AtcTag', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcFinding: {
    },
    AtcFindingList: {
      sequence: [
        { name: 'finding', type: 'AtcFinding', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcFindingReferences: {
      sequence: [
        { name: 'findingReference', type: 'AtcFindingReference', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcFindingReference: {
    },
    AtcItems: {
      sequence: [
        { name: 'item', type: 'AtcItem', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcItem: {
    },
    AtcRemarks: {
      sequence: [
        { name: 'remark', type: 'AtcRemark', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcRemark: {
    },
  },
} as const satisfies XsdSchema;
