/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/info
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.sap.com/adt/atc/info',
  prefix: 'info',
  root: 'info',
  elements: {
    AtcInfo: {
      sequence: [
        { name: 'type', type: 'string' },
        { name: 'description', type: 'string' },
      ],
    },
    AtcInfoList: {
      sequence: [
        { name: 'info', type: 'AtcInfo', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
