/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/object
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, atcfinding.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Atcfinding from './atcfinding';

export default {
  ns: 'http://www.sap.com/adt/atc/object',
  prefix: 'object',
  root: 'object',
  include: [Adtcore, Atcfinding],
  elements: {
    AtcObjectSetReference: {
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AtcObject: {
    },
    AtcObjectList: {
      sequence: [
        { name: 'object', type: 'AtcObject', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
