/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/resultquery
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.sap.com/adt/atc/resultquery',
  prefix: 'ns',
  root: 'userResultQuery',
  elements: {
    AtcResultQuery: {
      sequence: [
        { name: 'includeAggregates', type: 'boolean' },
        { name: 'includeFindings', type: 'boolean' },
        { name: 'contactPerson', type: 'string' },
      ],
    },
    ActiveAtcResultQuery: {
    },
    SpecificAtcResultQuery: {
    },
    UserAtcResultQuery: {
    },
  },
} as const satisfies XsdSchema;
