/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/result
 * Imports: atcresultquery.xsd, atcfinding.xsd, atcobject.xsd, atctagdescription.xsd, atcinfo.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atcresultquery from './atcresultquery';
import Atcfinding from './atcfinding';
import Atcobject from './atcobject';
import Atctagdescription from './atctagdescription';
import Atcinfo from './atcinfo';

export default {
  ns: 'http://www.sap.com/adt/atc/result',
  prefix: 'result',
  root: 'queryChoice',
  include: [Atcresultquery, Atcfinding, Atcobject, Atctagdescription, Atcinfo],
  elements: {
    AtcResult: {
      sequence: [
        { name: 'displayId', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'checkVariant', type: 'string' },
        { name: 'runSeries', type: 'string' },
        { name: 'createdAt', type: 'date' },
        { name: 'aggregates', type: 'AtcResultAggregates' },
        { name: 'objects', type: 'string' },
        { name: 'descriptionTags', type: 'DescriptionTags' },
        { name: 'infos', type: 'string' },
      ],
    },
    AtcResultAggregates: {
      sequence: [
        { name: 'numPrio1', type: 'number' },
        { name: 'numPrio2', type: 'number' },
        { name: 'numPrio3', type: 'number' },
        { name: 'numPrio4', type: 'number' },
        { name: 'numFailure', type: 'number' },
      ],
    },
    AtcResultList: {
      sequence: [
        { name: 'result', type: 'AtcResult', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcResultQueryChoice: {
      choice: [
        { name: 'activeResultQuery', type: 'ActiveResultQuery' },
        { name: 'specificResultQuery', type: 'SpecificResultQuery' },
        { name: 'userResultQuery', type: 'UserResultQuery' },
      ],
    },
  },
} as const satisfies XsdSchema;
