/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/tagdescription
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.sap.com/adt/atc/tagdescription',
  prefix: 'ns',
  root: 'descriptionTags',
  elements: {
    AtcTagDescription: {
      attributes: [
        { name: 'value', type: 'string' },
        { name: 'description', type: 'string' },
      ],
    },
    AtcTagDescriptions: {
      sequence: [
        { name: 'description', type: 'AtcTagDescription', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AtcTagWithDescr: {
      sequence: [
        { name: 'name', type: 'string' },
        { name: 'descriptions', type: 'AtcTagDescriptions' },
      ],
    },
    AtcTagWithDescrList: {
      sequence: [
        { name: 'tagWithDescription', type: 'AtcTagWithDescr', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
