/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/atc/worklist
 * Imports: atcinfo.xsd, atcobject.xsd, atctagdescription.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atcinfo from './atcinfo';
import Atcobject from './atcobject';
import Atctagdescription from './atctagdescription';

export default {
  ns: 'http://www.sap.com/adt/atc/worklist',
  prefix: 'worklist',
  root: 'worklistRun',
  include: [Atcinfo, Atcobject, Atctagdescription],
  elements: {
    AtcWorklist: {
      sequence: [
        { name: 'objectSets', type: 'AtcObjectSetList' },
        { name: 'objects', type: 'string' },
        { name: 'infos', type: 'string' },
      ],
      attributes: [
        { name: 'id', type: 'string', required: true },
        { name: 'timestamp', type: 'date', required: true },
        { name: 'usedObjectSet', type: 'string' },
        { name: 'objectSetIsComplete', type: 'boolean' },
      ],
    },
    AtcWorklistRun: {
      sequence: [
        { name: 'worklistId', type: 'string' },
        { name: 'worklistTimestamp', type: 'date' },
        { name: 'infos', type: 'string' },
      ],
    },
    AtcObjectSet: {
      attributes: [
        { name: 'name', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'kind', type: 'string' },
      ],
    },
    AtcObjectSetList: {
      sequence: [
        { name: 'objectSet', type: 'AtcObjectSet', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
