/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.w3.org/2005/Atom
 * Imports: xml.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Xml from './xml';

export default {
  ns: 'http://www.w3.org/2005/Atom',
  prefix: 'atom',
  root: 'link',
  include: [Xml],
  elements: {
    linkType: {
      attributes: [
        { name: 'href', type: 'string', required: true },
        { name: 'rel', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'hreflang', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'length', type: 'number' },
        { name: 'etag', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
