/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/abapxml/checklist
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/abapxml/checklist',
  prefix: 'checklist',
  root: 'messages',
  include: [Atom],
  elements: {
    MessageList: {
      sequence: [
        { name: 'msg', type: 'Message', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'properties', type: 'Properties' },
      ],
      attributes: [
        { name: 'forceSupported', type: 'boolean' },
      ],
    },
    Properties: {
      attributes: [
        { name: 'checkExecuted', type: 'boolean' },
        { name: 'activationExecuted', type: 'boolean' },
        { name: 'generationExecuted', type: 'boolean' },
      ],
    },
    Message: {
      sequence: [
        { name: 'shortText', type: 'TextList' },
        { name: 'longText', type: 'TextList', minOccurs: 0 },
        { name: 't100Key', type: 'T100Message', minOccurs: 0 },
        { name: 'correctionHint', type: 'CorrectionHint', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'link', type: 'Link', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'objDescr', type: 'string', required: true },
        { name: 'type', type: 'string', required: true },
        { name: 'line', type: 'number' },
        { name: 'offset', type: 'number' },
        { name: 'href', type: 'string' },
        { name: 'forceSupported', type: 'boolean' },
        { name: 'code', type: 'string' },
      ],
    },
    T100Message: {
      attributes: [
        { name: 'msgno', type: 'number' },
        { name: 'msgid', type: 'string' },
        { name: 'msgv1', type: 'string' },
        { name: 'msgv2', type: 'string' },
        { name: 'msgv3', type: 'string' },
        { name: 'msgv4', type: 'string' },
      ],
    },
    CorrectionHint: {
      attributes: [
        { name: 'number', type: 'number' },
        { name: 'kind', type: 'string' },
        { name: 'line', type: 'number' },
        { name: 'column', type: 'number' },
        { name: 'word', type: 'string' },
      ],
    },
    TextList: {
      sequence: [
        { name: 'txt', type: 'string', maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
