/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/oo/classes
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, abapoo.xsd, platform:/plugin/com.sap.adt.tools.abapsource/model/abapsource.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Abapoo from './abapoo';
import Abapsource from './abapsource';

export default {
  ns: 'http://www.sap.com/adt/oo/classes',
  prefix: 'classes',
  root: 'abapClassInclude',
  include: [Adtcore, Abapoo, Abapsource],
  elements: {
    AbapClass: {
    },
    AbapClassInclude: {
    },
  },
} as const satisfies XsdSchema;
