/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/configurations
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd, configuration.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';
import Configuration from './configuration';

export default {
  ns: 'http://www.sap.com/adt/configurations',
  prefix: 'ns',
  root: 'configurations',
  include: [Atom, Configuration],
  elements: {
    Configurations: {
      sequence: [
        { name: 'configuration', type: 'Configuration', maxOccurs: 'unbounded' },
      ],
    },
  },
} as const satisfies XsdSchema;
