/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/configuration
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/adt/configuration',
  prefix: 'ns',
  root: 'configuration',
  include: [Atom],
  elements: {
    Configuration: {
      sequence: [
        { name: 'properties', type: 'Properties' },
        { name: 'link', type: 'Link', minOccurs: 0 },
      ],
      attributes: [
        { name: 'client', type: 'string' },
        { name: 'configName', type: 'string' },
        { name: 'createdBy', type: 'string' },
        { name: 'createdAt', type: 'date' },
        { name: 'changedBy', type: 'string' },
        { name: 'changedAt', type: 'date' },
      ],
    },
    Properties: {
      sequence: [
        { name: 'property', type: 'Property', maxOccurs: 'unbounded' },
      ],
    },
    Property: {
      text: true,
      attributes: [
        { name: 'key', type: 'string' },
        { name: 'isMandatory', type: 'boolean' },
      ],
    },
  },
} as const satisfies XsdSchema;
