/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/debugger
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.sap.com/adt/debugger',
  prefix: 'debugger',
  root: 'memorySizes',
  elements: {
    MemorySizes: {
      sequence: [
        { name: 'abap', type: 'Abap', minOccurs: 0 },
        { name: 'internal', type: 'Internal' },
        { name: 'external', type: 'External' },
      ],
    },
    Abap: {
      sequence: [
        { name: 'staticVariables', type: 'number' },
        { name: 'stackUsed', type: 'number' },
        { name: 'stackAllocated', type: 'number' },
        { name: 'dynamicMemoryObjectsUsed', type: 'number' },
        { name: 'dynamicMemoryObjectsAllocated', type: 'number' },
      ],
    },
    Internal: {
      sequence: [
        { name: 'used', type: 'number' },
        { name: 'allocated', type: 'number' },
        { name: 'peakUsed', type: 'number' },
      ],
    },
    External: {
      sequence: [
        { name: 'used', type: 'number' },
        { name: 'allocated', type: 'number' },
        { name: 'peakUsed', type: 'number' },
        { name: 'numberOfInternalSessions', type: 'number' },
      ],
    },
  },
} as const satisfies XsdSchema;
