/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/ddic/ServiceConsumptionModel/http
 * Imports: properties.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Properties from './properties';

export default {
  ns: 'http://www.sap.com/adt/ddic/ServiceConsumptionModel/http',
  prefix: 'http',
  root: 'http',
  include: [Properties],
  elements: {
    Http: {
      sequence: [
        { name: 'properties', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
