/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/oo/interfaces
 * Imports: platform:/plugin/com.sap.adt.tools.abapsource/model/abapsource.xsd, abapoo.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Abapsource from './abapsource';
import Abapoo from './abapoo';

export default {
  ns: 'http://www.sap.com/adt/oo/interfaces',
  prefix: 'interfaces',
  root: 'abapInterface',
  include: [Abapsource, Abapoo],
  elements: {
    AbapInterface: {
    },
  },
} as const satisfies XsdSchema;
