/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/categories/dynamiclogpoints/logs
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd, platform:/plugin/com.sap.adt.logpoint/model/logpoint.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';
import Logpoint from './logpoint';

export default {
  ns: 'http://www.sap.com/adt/categories/dynamiclogpoints/logs',
  prefix: 'logs',
  root: 'collectionSummary',
  include: [Atom, Logpoint],
  elements: {
    AdtLogpointLogKeys: {
      sequence: [
        { name: 'progVersion', type: 'AdtLogpointProgVersion', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'null', type: 'string' },
      ],
    },
    AdtLogpointLogFieldList: {
      sequence: [
        { name: 'field', type: 'AdtLogpointLogField', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AdtLogpointLogEntry: {
      sequence: [
        { name: 'fieldList', type: 'AdtLogpointLogFieldList' },
      ],
    },
    AdtLogpointLogField: {
      sequence: [
        { name: 'value', type: 'AdtLogpointLogComponentValue' },
      ],
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtLogpointProgVersion: {
      sequence: [
        { name: 'key', type: 'AdtLogpointLogKey', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'generatedAt', type: 'date' },
      ],
    },
    AdtLogpointLogKey: {
      attributes: [
        { name: 'value', type: 'string' },
        { name: 'calls', type: 'number' },
        { name: 'lastCall', type: 'date' },
      ],
    },
    AdtLogpointLogComponentValue: {
    },
    AdtLogpointLogStructure: {
      sequence: [
        { name: 'c', type: 'AdtLogpointLogComponentValue', maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 't', type: 'boolean' },
      ],
    },
    AdtLogpointLogTable: {
      sequence: [
        { name: 'c', type: 'AdtLogpointLogComponentValue', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 't', type: 'boolean' },
      ],
    },
    AdtLogpointLogElementary: {
      attributes: [
        { name: 't', type: 'boolean' },
        { name: 'v', type: 'string' },
        { name: 'y', type: 'string' },
      ],
    },
    AdtLogCollectionSummary: {
      sequence: [
        { name: 'success', type: 'AdtLogCollectionSummaryServerList', minOccurs: 0 },
        { name: 'unreached', type: 'AdtLogCollectionSummaryServerList', minOccurs: 0 },
        { name: 'failed', type: 'AdtLogCollectionSummaryServerFailure', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'collectedLogs', type: 'number' },
      ],
    },
    AdtLogCollectionSummaryServerList: {
      sequence: [
        { name: 'server', type: 'string' },
      ],
    },
    AdtLogCollectionSummaryServerFailure: {
      attributes: [
        { name: 'server', type: 'string' },
        { name: 'returnCode', type: 'number' },
        { name: 'errorMessage', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
