/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/categories/dynamiclogpoints
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd, platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';
import Adtcore from './adtcore';

export default {
  ns: 'http://www.sap.com/adt/categories/dynamiclogpoints',
  prefix: 'ns',
  root: 'locationCheck',
  include: [Atom, Adtcore],
  elements: {
    AdtLogpointDefinition: {
      attributes: [
        { name: 'description', type: 'string' },
        { name: 'subKey', type: 'string' },
        { name: 'fields', type: 'string' },
        { name: 'condition', type: 'string' },
        { name: 'rollareaCounter', type: 'number' },
        { name: 'usageType', type: 'string' },
        { name: 'createdBy', type: 'string' },
        { name: 'changedBy', type: 'string' },
        { name: 'changedAt', type: 'date' },
        { name: 'expiresAt', type: 'date' },
        { name: 'activityType', type: 'string' },
        { name: 'retentionTimeInDays', type: 'number' },
      ],
    },
    AdtLogpointActivation: {
      sequence: [
        { name: 'users', type: 'AdtLogpointUserList', minOccurs: 0 },
        { name: 'servers', type: 'AdtLogpointServerList', minOccurs: 0 },
      ],
      attributes: [
        { name: 'state', type: 'string' },
        { name: 'activatedBy', type: 'string' },
        { name: 'activeSince', type: 'date' },
        { name: 'activeUntil', type: 'date' },
        { name: 'inactivatedBy', type: 'string' },
        { name: 'inactiveSince', type: 'date' },
      ],
    },
    AdtLogpointUserList: {
      sequence: [
        { name: 'user', type: 'AdtLogpointUser', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AdtLogpointUser: {
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtLogpointServerList: {
      sequence: [
        { name: 'server', type: 'AdtLogpointServer', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    AdtLogpointServer: {
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtLogpoint: {
      sequence: [
        { name: 'location', type: 'AdtLogpointLocationInfo', minOccurs: 0 },
        { name: 'definition', type: 'AdtLogpointDefinition', minOccurs: 0 },
        { name: 'activation', type: 'AdtLogpointActivation', minOccurs: 0 },
      ],
    },
    AdtLogpointList: {
      sequence: [
        { name: 'logpoint', type: 'AdtLogpointEntry' },
      ],
    },
    AdtLogpointEntry: {
      sequence: [
        { name: 'summary', type: 'AdtLogpointSummary', minOccurs: 0 },
        { name: 'definition', type: 'AdtLogpointDefinition', minOccurs: 0 },
        { name: 'activation', type: 'AdtLogpointActivation', minOccurs: 0 },
        { name: 'location', type: 'AdtLogpointLocationInfo', minOccurs: 0 },
      ],
    },
    AdtLogpointSummary: {
      sequence: [
        { name: 'shortInfo', type: 'string' },
        { name: 'executions', type: 'number' },
      ],
    },
    AdtLogpointLocationCheck: {
      sequence: [
        { name: 'location', type: 'AdtLogpointLocationInfo', minOccurs: 0 },
      ],
      attributes: [
        { name: 'message', type: 'string' },
        { name: 'possible', type: 'boolean' },
      ],
    },
    AdtLogpointProgram: {
      attributes: [
        { name: 'name', type: 'string' },
      ],
    },
    AdtLogpointLocationInfo: {
      sequence: [
        { name: 'includePosition', type: 'string', minOccurs: 0 },
        { name: 'mainProgram', type: 'string', minOccurs: 0 },
      ],
    },
  },
} as const satisfies XsdSchema;
