/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/quickfixes
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';
import Atom from './atom';

export default {
  ns: 'http://www.sap.com/adt/quickfixes',
  prefix: 'quickfixes',
  root: 'proposalResult',
  include: [Adtcore, Atom],
  elements: {
    EvaluationRequest: {
      sequence: [
        { name: 'affectedObjects', type: 'AffectedObjectsWithSource', minOccurs: 0 },
      ],
    },
    EvaluationResults: {
      sequence: [
        { name: 'evaluationResult', type: 'EvaluationResult', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    EvaluationResult: {
      sequence: [
        { name: 'userContent', type: 'string', minOccurs: 0 },
        { name: 'affectedObjects', type: 'AffectedObjectsWithoutSource', minOccurs: 0 },
      ],
    },
    AffectedObjectsWithoutSource: {
    },
    ProposalRequest: {
      sequence: [
        { name: 'input', type: 'Unit' },
        { name: 'affectedObjects', type: 'AffectedObjectsWithSource', minOccurs: 0 },
        { name: 'userContent', type: 'string', minOccurs: 0 },
      ],
    },
    AffectedObjectsWithSource: {
      sequence: [
        { name: 'unit', type: 'Unit', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    ProposalResult: {
      sequence: [
        { name: 'deltas', type: 'Deltas' },
        { name: 'selection', type: 'string', minOccurs: 0 },
        { name: 'variableSourceStates', type: 'VariableSourceStates', minOccurs: 0 },
        { name: 'statusMessages', type: 'StatusMessages', minOccurs: 0 },
      ],
    },
    Deltas: {
      sequence: [
        { name: 'unit', type: 'Unit', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    Unit: {
      sequence: [
        { name: 'content', type: 'string' },
      ],
    },
    VariableSourceStates: {
      attributes: [
        { name: 'keepCursor', type: 'boolean' },
      ],
    },
    StatusMessages: {
      sequence: [
        { name: 'statusMessage', type: 'StatusMessage', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    StatusMessage: {
      attributes: [
        { name: 'severity', type: 'string', required: true },
        { name: 'message', type: 'string', required: true },
        { name: 'id', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
