/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/adt/crosstrace/traces
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Adtcore from './adtcore';

export default {
  ns: 'http://www.sap.com/adt/crosstrace/traces',
  prefix: 'traces',
  root: 'uriMapping',
  include: [Adtcore],
  elements: {
    Activations: {
      sequence: [
        { name: 'activation', type: 'Activation', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    Activation: {
      sequence: [
        { name: 'activationId', type: 'string' },
        { name: 'deletionTime', type: 'date' },
        { name: 'description', type: 'string' },
        { name: 'enabled', type: 'boolean' },
        { name: 'userFilter', type: 'string' },
        { name: 'serverFilter', type: 'string' },
        { name: 'requestTypeFilter', type: 'string' },
        { name: 'requestNameFilter', type: 'string' },
        { name: 'sensitiveDataAllowed', type: 'boolean' },
        { name: 'createUser', type: 'string' },
        { name: 'createTime', type: 'date' },
        { name: 'changeUser', type: 'string' },
        { name: 'changeTime', type: 'date' },
        { name: 'components', type: 'Components' },
        { name: 'numberOfTraces', type: 'number', minOccurs: 0 },
        { name: 'maxNumberOfTraces', type: 'number', minOccurs: 0 },
        { name: 'noContent', type: 'boolean', minOccurs: 0 },
      ],
    },
    Components: {
      sequence: [
        { name: 'component', type: 'Component', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    Component: {
      sequence: [
        { name: 'component', type: 'string' },
        { name: 'traceLevel', type: 'number' },
      ],
    },
    Traces: {
      sequence: [
        { name: 'trace', type: 'Trace', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    ComponentNames: {
      sequence: [
        { name: 'componentName', type: 'string', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    RecordsSummary: {
      sequence: [
        { name: 'componentNames', type: 'ComponentNames', minOccurs: 0 },
        { name: 'numberOfRecords', type: 'number' },
        { name: 'minRecordsTimestamp', type: 'date' },
        { name: 'maxRecordsTimestamp', type: 'date' },
        { name: 'contentSize', type: 'number' },
      ],
    },
    Trace: {
      sequence: [
        { name: 'traceId', type: 'string' },
        { name: 'user', type: 'string' },
        { name: 'server', type: 'string' },
        { name: 'creationTime', type: 'date' },
        { name: 'description', type: 'string' },
        { name: 'deletionTime', type: 'date' },
        { name: 'requestType', type: 'string' },
        { name: 'requestName', type: 'string' },
        { name: 'eppTransactionId', type: 'string' },
        { name: 'eppRootContextId', type: 'string' },
        { name: 'eppConnectionId', type: 'string' },
        { name: 'eppConnectionCounter', type: 'number' },
        { name: 'properties', type: 'Properties' },
        { name: 'activation', type: 'Activation', minOccurs: 0 },
        { name: 'recordsSummary', type: 'RecordsSummary', minOccurs: 0 },
        { name: 'originalImportMetadata', type: 'ImportMetadata', minOccurs: 0 },
      ],
    },
    Options: {
      attributes: [
        { name: 'noSensitiveData', type: 'boolean' },
        { name: 'callStackOffset', type: 'number' },
        { name: 'fullCallStack', type: 'boolean' },
        { name: 'highlighting', type: 'string' },
      ],
    },
    Properties: {
      sequence: [
        { name: 'property', type: 'Property', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    ImportMetadata: {
      sequence: [
        { name: 'originalTraceId', type: 'string' },
        { name: 'originalTraceSystem', type: 'string' },
        { name: 'originalTraceClient', type: 'string' },
        { name: 'originalTraceServer', type: 'string' },
        { name: 'originalTraceUser', type: 'string' },
        { name: 'originalChangeUser', type: 'string' },
        { name: 'originalCreateUser', type: 'string' },
        { name: 'originalHeaderUserAttributeDev', type: 'string' },
        { name: 'originalHeaderTimestamp', type: 'date' },
      ],
    },
    Property: {
      sequence: [
        { name: 'component', type: 'string' },
        { name: 'key', type: 'string' },
        { name: 'value', type: 'string' },
      ],
    },
    Records: {
      sequence: [
        { name: 'record', type: 'Record', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    Record: {
      sequence: [
        { name: 'traceId', type: 'string' },
        { name: 'recordNumber', type: 'number' },
        { name: 'parentNumber', type: 'number', minOccurs: 0 },
        { name: 'creationTime', type: 'date' },
        { name: 'traceComponent', type: 'string', minOccurs: 0 },
        { name: 'traceObject', type: 'string', minOccurs: 0 },
        { name: 'traceProcedure', type: 'string', minOccurs: 0 },
        { name: 'traceLevel', type: 'number' },
        { name: 'callStack', type: 'string', minOccurs: 0 },
        { name: 'message', type: 'string', minOccurs: 0 },
        { name: 'contentType', type: 'string', minOccurs: 0 },
        { name: 'hierarchyType', type: 'string', minOccurs: 0 },
        { name: 'hierarchyNumber', type: 'number', minOccurs: 0 },
        { name: 'hierarchiesLevel', type: 'number', minOccurs: 0 },
        { name: 'content', type: 'string', minOccurs: 0 },
        { name: 'contentLength', type: 'number', minOccurs: 0 },
        { name: 'properties', type: 'Properties', minOccurs: 0 },
        { name: 'options', type: 'Options', minOccurs: 0 },
        { name: 'processedObjects', type: 'string', minOccurs: 0 },
      ],
    },
    UriMapping: {
    },
  },
} as const satisfies XsdSchema;
