/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/cts/adt/transports/search
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd, platform:/plugin/org.eclipse.emf.ecore/model/Ecore.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';
import Ecore from './Ecore';

export default {
  ns: 'http://www.sap.com/cts/adt/transports/search',
  prefix: 'search',
  root: 'searchresults',
  include: [Atom, Ecore],
  elements: {
    requests: {
      sequence: [
        { name: 'request', type: 'request', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    request: {
      sequence: [
        { name: 'link', type: 'Link', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'tasks', type: 'string', minOccurs: 0 },
      ],
      attributes: [
        { name: 'number', type: 'string' },
        { name: 'owner', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'target', type: 'string' },
        { name: 'status', type: 'string' },
      ],
    },
    tasks: {
      sequence: [
        { name: 'task', type: 'string', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    task: {
      sequence: [
        { name: 'link', type: 'Link', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'number', type: 'string' },
        { name: 'owner', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'parent', type: 'string' },
      ],
    },
    searchresults: {
      sequence: [
        { name: 'requests', type: 'string', minOccurs: 0 },
        { name: 'tasks', type: 'string', minOccurs: 0 },
      ],
    },
  },
} as const satisfies XsdSchema;
