/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.sap.com/cts/adt/tm
 * Imports: platform:/plugin/com.sap.adt.tools.core.base/model/atom.xsd, platform:/plugin/com.sap.adt.tools.core.base/model/adtcore.xsd, platform:/plugin/com.sap.adt.tools.core/model/checkrun.xsd
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';
import Atom from './atom';
import Adtcore from './adtcore';
import Checkrun from './checkrun';

export default {
  ns: 'http://www.sap.com/cts/adt/tm',
  prefix: 'tm',
  root: 'root',
  include: [Atom, Adtcore, Checkrun],
  elements: {
    ProjectProvider: {
    },
    Adaptable: {
    },
    root: {
      sequence: [
        { name: 'workbench', type: 'workbench' },
        { name: 'customizing', type: 'customizing' },
        { name: 'releasereports', type: 'string' },
      ],
      attributes: [
        { name: 'targetuser', type: 'string' },
        { name: 'useraction', type: 'string' },
        { name: 'releasetimestamp', type: 'string' },
        { name: 'releaseobjlock', type: 'string' },
        { name: 'number', type: 'string' },
        { name: 'desc', type: 'string' },
        { name: 'uri', type: 'string' },
      ],
    },
    workbench: {
      sequence: [
        { name: 'target', type: 'target', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'modifiable', type: 'modifiable' },
        { name: 'relstarted', type: 'relstarted' },
        { name: 'released', type: 'released' },
      ],
      attributes: [
        { name: 'category', type: 'string' },
      ],
    },
    modifiable: {
      sequence: [
        { name: 'request', type: 'request', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'status', type: 'string' },
      ],
    },
    relstarted: {
      sequence: [
        { name: 'request', type: 'request', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'status', type: 'string' },
      ],
    },
    released: {
      sequence: [
        { name: 'request', type: 'request', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'status', type: 'string' },
      ],
    },
    customizing: {
      sequence: [
        { name: 'target', type: 'target', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'modifiable', type: 'modifiable' },
        { name: 'relstarted', type: 'relstarted' },
        { name: 'released', type: 'released' },
      ],
      attributes: [
        { name: 'category', type: 'string' },
      ],
    },
    target: {
      sequence: [
        { name: 'modifiable', type: 'modifiable' },
        { name: 'relstarted', type: 'relstarted' },
        { name: 'released', type: 'released' },
      ],
      attributes: [
        { name: 'name', type: 'string' },
        { name: 'desc', type: 'string' },
      ],
    },
    request: {
      sequence: [
        { name: 'task', type: 'task', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'link', type: 'Link', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'abap_object', type: 'abap_object', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'number', type: 'string' },
        { name: 'owner', type: 'string' },
        { name: 'desc', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'uri', type: 'string' },
      ],
    },
    task: {
      sequence: [
        { name: 'abap_object', type: 'abap_object', minOccurs: 0, maxOccurs: 'unbounded' },
        { name: 'link', type: 'Link', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
      attributes: [
        { name: 'number', type: 'string' },
        { name: 'owner', type: 'string' },
        { name: 'desc', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'uri', type: 'string' },
      ],
    },
    abap_object: {
      attributes: [
        { name: 'pgmid', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'wbtype', type: 'string' },
        { name: 'uri', type: 'string' },
        { name: 'dummy_uri', type: 'string' },
        { name: 'obj_info', type: 'string' },
        { name: 'obj_desc', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;
