/**
 * Auto-generated ts-xsd schema
 * Namespace: http://www.w3.org/XML/1998/namespace
 * Generated by ts-xsd
 */

import type { XsdSchema } from 'ts-xsd';

export default {
  ns: 'http://www.w3.org/XML/1998/namespace',
  prefix: 'namespace',
  elements: {
  },
} as const satisfies XsdSchema;
