import { InterfaceAdtSchema } from '@abapify/adt-schemas';

import type { AdkObjectConstructor } from '../../base/adk-object';
import { createAdkObject } from '../../base/class-factory';
import { Kind } from '../../registry';


/**
 * ABAP Interface object
 *
 * Generated by createAdkObject factory.
 * Delegates all XML I/O to InterfaceAdtSchema.
 */
export const Interface = createAdkObject(Kind.Interface, InterfaceAdtSchema);

// Export constructor type for registry
export const InterfaceConstructor: AdkObjectConstructor<InstanceType<typeof Interface>> = Interface;

// Export type
export type Interface = InstanceType<typeof Interface>;
