/**
 * Auto-generated route manifest
 * DO NOT EDIT - Generated by scripts/generate-routes.ts
 */

import { default as Page0 } from './sap/bc/adt/cts/transportrequests/[slug]';
import type { PageComponent } from '../lib/types';

export interface Route {
  pattern: string;
  regex: RegExp;
  page: PageComponent;
}

export const routes: Route[] = [
  {
    pattern: '/sap/bc/adt/cts/transportrequests/:slug',
    regex: new RegExp('^/sap\/bc\/adt\/cts\/transportrequests\/([^\/]+)$'),
    page: Page0,
  }
];

/**
 * Match URL to route
 */
export function matchRoute(url: string): Route | null {
  for (const route of routes) {
    if (route.regex.test(url)) {
      return route;
    }
  }
  return null;
}
