auth:
  type: btp
  btp:
    serviceKey: ${BTP_SERVICE_KEY_PATH}

plugins:
  formats:
    - name: '@abapify/oat'
      config:
        enabled: true
        options:
          fileStructure: hierarchical
          includeMetadata: true
          packageMapping:
            finance: ZTEAMA_FIN
            basis: ZTEAMA_BASIS
    - name: '@abapify/abapgit'
      config:
        enabled: true
        options:
          xmlFormat: true
          includeInactive: false
    - name: '@company/custom-format'
      config:
        enabled: false
        options:
          customOption: value

defaults:
  format: oat
  outputPath: ./output
  objectTypes:
    - CLAS
    - INTF
    - DDLS
    - FUGR
