/**
 * Generator Tests
 * 
 * Tests for factory and raw generators
 */

import { describe, test as it } from 'node:test';
import { strict as assert } from 'node:assert';
import { factory, raw } from '../../src/generators';
import type { GeneratorContext, SchemaData } from '../../src/codegen/generator';

describe('generators', () => {
  // Sample schema data for testing (new format)
  const sampleSchema: SchemaData = {
    namespace: 'http://example.com/test',
    prefix: 'test',
    imports: [],
    element: [
      { name: 'Person', type: 'Person' },
    ],
    complexType: {
      Person: {
        sequence: [
          { name: 'name', type: 'string' },
          { name: 'age', type: 'number', minOccurs: 0 },
        ],
        attributes: [
          { name: 'id', type: 'string', required: true },
        ],
      },
    },
  };

  const schemaWithImports: SchemaData = {
    namespace: 'http://example.com/customer',
    prefix: 'cust',
    imports: [
      { name: 'Common', path: './common', namespace: 'http://example.com/common' },
      { name: 'Address', path: './address', namespace: 'http://example.com/address' },
    ],
    element: [
      { name: 'Customer', type: 'Customer' },
    ],
    complexType: {
      Customer: {
        sequence: [
          { name: 'name', type: 'string' },
          { name: 'address', type: 'AddressType' },
        ],
      },
    },
  };

  describe('factory generator', () => {
    it('should generate code with default factory path', () => {
      const gen = factory();
      const ctx: GeneratorContext = { schema: sampleSchema, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import schema from '../schema'"));
      assert.ok(code.includes('export default schema('));
      assert.ok(code.includes("ns: 'http://example.com/test'"));
      assert.ok(code.includes("prefix: 'test'"));
      assert.ok(code.includes('as const'));
    });

    it('should generate code with custom factory path', () => {
      const gen = factory({ path: '../../speci' });
      const ctx: GeneratorContext = { schema: sampleSchema, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import schema from '../../speci'"));
    });

    it('should generate imports for dependencies', () => {
      const gen = factory();
      const ctx: GeneratorContext = { schema: schemaWithImports, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import Common from './common'"));
      assert.ok(code.includes("import Address from './address'"));
      assert.ok(code.includes('include: [Common, Address]'));
    });

    it('should generate index file', () => {
      const gen = factory();
      const schemas = ['person', 'address', 'customer-order'];
      
      const indexCode = gen.generateIndex?.(schemas);
      
      assert.ok(indexCode?.includes("export { default as person } from './person'"));
      assert.ok(indexCode?.includes("export { default as address } from './address'"));
      // Should convert hyphenated names to camelCase
      assert.ok(indexCode?.includes("export { default as customerOrder } from './customer-order'"));
    });

    it('should generate stub for missing schema', () => {
      const gen = factory();
      
      const stubCode = gen.generateStub?.('missing-schema');
      
      assert.ok(stubCode?.includes('Stub schema for missing-schema'));
      assert.ok(stubCode?.includes("import schema from '../schema'"));
      assert.ok(stubCode?.includes('export default schema('));
    });

    it('should include header comment with namespace', () => {
      const gen = factory();
      const ctx: GeneratorContext = { schema: sampleSchema, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes('Auto-generated ts-xsd schema'));
      assert.ok(code.includes('Namespace: http://example.com/test'));
      assert.ok(code.includes('Generated by ts-xsd (factory generator)'));
    });

    it('should include imports in header comment', () => {
      const gen = factory();
      const ctx: GeneratorContext = { schema: schemaWithImports, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes('Imports: ./common, ./address'));
    });
  });

  describe('raw generator', () => {
    it('should generate code with XsdSchema type', () => {
      const gen = raw();
      const ctx: GeneratorContext = { schema: sampleSchema, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import type { XsdSchema } from 'ts-xsd'"));
      assert.ok(code.includes('export default {'));
      assert.ok(code.includes('as const satisfies XsdSchema'));
    });

    it('should generate code with custom types import path', () => {
      const gen = raw({ typesFrom: '../types' });
      const ctx: GeneratorContext = { schema: sampleSchema, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import type { XsdSchema } from '../types'"));
    });

    it('should generate imports for dependencies', () => {
      const gen = raw();
      const ctx: GeneratorContext = { schema: schemaWithImports, args: {} };
      
      const code = gen.generate(ctx);
      
      assert.ok(code.includes("import Common from './common'"));
      assert.ok(code.includes("import Address from './address'"));
    });

    it('should generate index file', () => {
      const gen = raw();
      const schemas = ['person', 'address'];
      
      const indexCode = gen.generateIndex?.(schemas);
      
      assert.ok(indexCode?.includes("export { default as person } from './person'"));
      assert.ok(indexCode?.includes("export { default as address } from './address'"));
    });

    it('should generate stub for missing schema', () => {
      const gen = raw();
      
      const stubCode = gen.generateStub?.('missing');
      
      assert.ok(stubCode?.includes('Stub schema for missing'));
      assert.ok(stubCode?.includes("import type { XsdSchema } from 'ts-xsd'"));
    });
  });
});
