/**
 * Auto-generated ts-xsd schema
 * Namespace: http://example.com/order
 * Generated by ts-xsd
 */

import type { XsdSchema, InferXsd } from 'ts-xsd';

export const Order = {
  ns: 'http://example.com/order',
  prefix: 'ord',
  root: 'Order',
  elements: {
    Order: {
      sequence: [
        { name: 'customer', type: 'string' },
        { name: 'items', type: 'ItemsType' },
        { name: 'total', type: 'number' },
      ],
      attributes: [
        { name: 'id', type: 'string', required: true },
        { name: 'date', type: 'date' },
      ],
    },
    ItemsType: {
      sequence: [
        { name: 'item', type: 'ItemType', minOccurs: 0, maxOccurs: 'unbounded' },
      ],
    },
    ItemType: {
      sequence: [
        { name: 'name', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'price', type: 'number' },
      ],
      attributes: [
        { name: 'sku', type: 'string', required: true },
      ],
    },
  },
} as const satisfies XsdSchema;

export type OrderType = InferXsd<typeof Order>;
