/**
 * Auto-generated ts-xsd schema
 * Namespace: http://example.com/person
 * Generated by ts-xsd
 */

import type { XsdSchema, InferXsd } from 'ts-xsd';

export const Person = {
  ns: 'http://example.com/person',
  prefix: 'per',
  root: 'Person',
  elements: {
    Person: {
      sequence: [
        { name: 'FirstName', type: 'string' },
        { name: 'LastName', type: 'string' },
        { name: 'Age', type: 'number', minOccurs: 0 },
        { name: 'Email', type: 'string', minOccurs: 0 },
      ],
      attributes: [
        { name: 'id', type: 'string', required: true },
        { name: 'status', type: 'string' },
      ],
    },
  },
} as const satisfies XsdSchema;

export type PersonType = InferXsd<typeof Person>;
